name: Automated tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOTNET_NOLOGO: true

    steps:
      - uses: actions/checkout@v6
      - name: Setup Redis
        uses: zhulik/redis-action@1.1.0
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: |
            10.x
            8.x
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Test
        run: dotnet test --no-restore
